/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipe"];
        put: operations["save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/rollback/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["relationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/history/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historyVersion_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/model/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/dom/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["expressions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ddl/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ddl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonNode: Record<string, never>;
        RecipeSaveRequestDto: {
            baseModified?: string;
            content?: components["schemas"]["JsonNode"];
        };
        RecipeDto: {
            path?: string;
            fileName?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            content?: components["schemas"]["JsonNode"];
        };
        RecipeValidationDto: {
            valid?: boolean;
            errors?: components["schemas"]["RecipeValidationErrorDto"][];
        };
        RecipeValidationErrorDto: {
            path?: string;
            message?: string;
        };
        TreeNodeDto: {
            name?: string;
            path?: string;
            kind?: string;
            layer?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            mappingPath?: string;
            hasRecipe?: boolean;
            hasDdl?: boolean;
            children?: components["schemas"]["TreeNodeDto"][];
        };
        EdgeDto: {
            from?: string;
            to?: string;
            kind?: string;
        };
        MetaDto: {
            /** Format: int32 */
            entryCount?: number;
            /** Format: int32 */
            skippedRows?: number;
            layers?: string[];
        };
        NodeDto: {
            id?: string;
            kind?: string;
            name?: string;
            layer?: string;
            mappingPath?: string;
            hasRecipe?: boolean;
            workflow?: string;
            /** Format: int32 */
            executionOrder?: number;
            writeMode?: string;
            partitionType?: string;
        };
        RelationshipsDto: {
            nodes?: components["schemas"]["NodeDto"][];
            edges?: components["schemas"]["EdgeDto"][];
            meta?: components["schemas"]["MetaDto"];
        };
        RecipeHistoryEntryDto: {
            version?: string;
            timestamp?: string;
            /** Format: int64 */
            sizeBytes?: number;
        };
        B15RowDto: {
            clusterName?: string;
            recipeFilename?: string;
            jobId?: string;
            appStartIso?: string;
            avgJobDurationInMinsSec?: string;
            status?: string;
            message?: string;
        };
        OperationalSnapshotDto: {
            date?: string;
            rows?: components["schemas"]["B15RowDto"][];
        };
        HistoryEntryDto: {
            date?: string;
            status?: string;
            /** Format: double */
            durationMin?: number;
        };
        OperationalSummaryDto: {
            dates?: string[];
            recipes?: components["schemas"]["RecipeSummaryDto"][];
        };
        RecipeSummaryDto: {
            recipeFilename?: string;
            layer?: string;
            latestDate?: string;
            latestStatus?: string;
            /** Format: int32 */
            okCount?: number;
            /** Format: int32 */
            koCount?: number;
            history?: components["schemas"]["HistoryEntryDto"][];
            /** Format: double */
            avgDurationMin?: number;
            /** Format: double */
            p50DurationMin?: number;
            /** Format: double */
            p95DurationMin?: number;
            lastJobId?: string;
            lastClusterName?: string;
        };
        OperationalDatesDto: {
            dates?: string[];
            mode?: string;
        };
        ConnectorDto: {
            fromField?: string;
            fromInstance?: string;
            fromInstanceType?: string;
            toField?: string;
            toInstance?: string;
            toInstanceType?: string;
        };
        FieldDependencyDto: {
            inputField?: string;
            outputField?: string;
        };
        FolderDto: {
            name?: string;
            group?: string;
            owner?: string;
            shared?: string;
            description?: string;
            permissions?: string;
            uuid?: string;
            sources?: components["schemas"]["SourceDto"][];
            targets?: components["schemas"]["TargetDto"][];
            transformations?: components["schemas"]["TransformationDto"][];
            mapplets?: components["schemas"]["MappletDto"][];
            mappings?: components["schemas"]["MappingDto"][];
        };
        GroupDto: {
            description?: string;
            name?: string;
            expression?: string;
            order?: string;
            type?: string;
        };
        InstanceDto: {
            description?: string;
            name?: string;
            reusable?: string;
            transformationName?: string;
            transformationType?: string;
            tType?: string;
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
        };
        MappingDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            targetLoader?: components["schemas"]["TargetLoaderDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MappingModelDto: {
            creationDate?: string;
            repositoryVersion?: string;
            repository?: components["schemas"]["RepositoryDto"];
        };
        MappingVariableDto: {
            aggfunction?: string;
            dataType?: string;
            defaultValue?: string;
            description?: string;
            isExpressionVariable?: string;
            isParam?: string;
            name?: string;
            precision?: string;
            scale?: string;
            userDefined?: string;
        };
        MappletDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MetadataExtensionDto: {
            datatype?: string;
            description?: string;
            domainname?: string;
            isclienteditable?: string;
            isclientvisible?: string;
            isreusable?: string;
            isshareread?: string;
            issharewrite?: string;
            maxlength?: string;
            name?: string;
            value?: string;
            vendorname?: string;
        };
        RepositoryDto: {
            name?: string;
            version?: string;
            codepage?: string;
            databaseType?: string;
            folder?: components["schemas"]["FolderDto"];
        };
        SourceDto: {
            name?: string;
            businessname?: string;
            databasetype?: string;
            dbdname?: string;
            description?: string;
            objectversion?: string;
            ownername?: string;
            versionnumber?: string;
            sourceFields?: components["schemas"]["SourceFieldDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
        };
        SourceFieldDto: {
            businessname?: string;
            dataType?: string;
            description?: string;
            fieldnumber?: string;
            fieldproperty?: string;
            fieldType?: string;
            hidden?: string;
            keyType?: string;
            length?: string;
            level?: string;
            name?: string;
            nullable?: string;
            occurs?: string;
            offset?: string;
            physicallength?: string;
            physicaloffset?: string;
            picturetext?: string;
            precision?: string;
            scale?: string;
            usageflags?: string;
        };
        TableAttributeDto: {
            name?: string;
            value?: string;
        };
        TargetDto: {
            businessName?: string;
            constraint?: string;
            databaseType?: string;
            description?: string;
            name?: string;
            objectVersion?: string;
            tableOptions?: string;
            versionNumber?: string;
            targetFields?: components["schemas"]["TargetFieldDto"][];
        };
        TargetFieldDto: {
            businessName?: string;
            dataType?: string;
            description?: string;
            /** Format: int32 */
            fieldNumber?: number;
            keyType?: string;
            name?: string;
            nullable?: string;
            pictureText?: string;
            precision?: string;
            scale?: string;
        };
        TargetLoaderDto: {
            order?: string;
            targetInstance?: string;
        };
        TransformFieldDto: {
            dataType?: string;
            name?: string;
            defaultValue?: string;
            description?: string;
            group?: string;
            expression?: string;
            expressionType?: string;
            mappletGroup?: string;
            pictureText?: string;
            portType?: string;
            precision?: string;
            refField?: string;
            refInstanceType?: string;
            refSourceField?: string;
            scale?: string;
        };
        TransformationDto: {
            description?: string;
            name?: string;
            objectVersion?: string;
            reusable?: string;
            typ?: string;
            templateName?: string;
            versionNumber?: string;
            transformFields?: components["schemas"]["TransformFieldDto"][];
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
            groups?: components["schemas"]["GroupDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
            fieldDependencies?: components["schemas"]["FieldDependencyDto"][];
            sourceFields?: components["schemas"]["SourceFieldDto"][];
        };
        XmlNodeDto: {
            name?: string;
            attributes?: {
                [key: string]: string;
            };
            text?: string;
            children?: components["schemas"]["XmlNodeDto"][];
        };
        ExpressionEntryDto: {
            mappingPath?: string;
            layer?: string;
            transformation?: string;
            port?: string;
            formula?: string;
            origin?: string;
        };
        AppConfigDto: {
            projectId?: string;
            region?: string;
            dataprocJobUrl?: string;
            dataprocClusterUrl?: string;
            loggingUrl?: string;
            dwhControlMode?: string;
            composerMode?: string;
            corpusRoot?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeSaveRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeValidationDto"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query: {
                version: string;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeNodeDto"];
                };
            };
        };
    };
    relationships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RelationshipsDto"];
                };
            };
        };
    };
    historyVersion_1: {
        parameters: {
            query: {
                version: string;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeHistoryEntryDto"][] | components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalSnapshotDto"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalSummaryDto"];
                };
            };
        };
    };
    dates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalDatesDto"];
                };
            };
        };
    };
    model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MappingModelDto"];
                };
            };
        };
    };
    dom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["XmlNodeDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    expressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpressionEntryDto"][];
                };
            };
        };
    };
    ddl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["JsonNode"];
                    };
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppConfigDto"];
                };
            };
        };
    };
}
