/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipe"];
        put: operations["save"];
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layouts/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["layout"];
        put: operations["save_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/rollback/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipc/fan-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fanIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["relationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["registry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/history/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["historyVersion_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operational/clusters/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cluster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/model/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/dom/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ipc/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["expressions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["diagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ddl/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ddl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonNode: Record<string, never>;
        RecipeSaveRequestDto: {
            baseModified?: string;
            content?: components["schemas"]["JsonNode"];
        };
        RecipeDto: {
            path?: string;
            fileName?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            content?: components["schemas"]["JsonNode"];
        };
        LayoutDto: {
            /** Format: int32 */
            version?: number;
            nodes?: {
                [key: string]: components["schemas"]["NodeOffsetDto"];
            };
        };
        NodeOffsetDto: {
            /** Format: double */
            dx?: number;
            /** Format: double */
            dy?: number;
        };
        IpcCheckDto: {
            ruleId?: string;
            severity?: string;
            status?: string;
            path?: string;
            message?: string;
        };
        RecipeValidationDto: {
            valid?: boolean;
            errors?: components["schemas"]["RecipeValidationErrorDto"][];
            warnings?: components["schemas"]["RecipeValidationErrorDto"][];
            checks?: components["schemas"]["IpcCheckDto"][];
        };
        RecipeValidationErrorDto: {
            path?: string;
            message?: string;
        };
        FanInPairingDto: {
            key?: string;
            existingSourceKinds?: string[];
            candidateKind?: string;
        };
        FanInRequestDto: {
            pairings?: components["schemas"]["FanInPairingDto"][];
        };
        FanInVerdictsDto: {
            verdicts?: {
                [key: string]: string;
            };
        };
        TreeNodeDto: {
            name?: string;
            path?: string;
            kind?: string;
            layer?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            mappingPath?: string;
            hasRecipe?: boolean;
            hasDdl?: boolean;
            children?: components["schemas"]["TreeNodeDto"][];
        };
        SummaryDto: {
            /** Format: int32 */
            xmlCount?: number;
            /** Format: int32 */
            recipeCount?: number;
            /** Format: int32 */
            ddlCount?: number;
            /** Format: int32 */
            dirCount?: number;
            layers?: string[];
        };
        EdgeDto: {
            from?: string;
            to?: string;
            kind?: string;
        };
        MetaDto: {
            /** Format: int32 */
            entryCount?: number;
            /** Format: int32 */
            skippedRows?: number;
            layers?: string[];
            scopedClusters?: string[];
            /** Format: int32 */
            neighborCount?: number;
        };
        NodeDto: {
            id?: string;
            kind?: string;
            name?: string;
            layer?: string;
            mappingPath?: string;
            hasRecipe?: boolean;
            workflow?: string;
            /** Format: int32 */
            executionOrder?: number;
            writeMode?: string;
            partitionType?: string;
            clusterNames?: string[];
            neighbor?: boolean;
        };
        RelationshipsDto: {
            nodes?: components["schemas"]["NodeDto"][];
            edges?: components["schemas"]["EdgeDto"][];
            meta?: components["schemas"]["MetaDto"];
        };
        RegistryColumnDto: {
            name?: string;
            type?: string;
        };
        RegistryDto: {
            sourceTables?: components["schemas"]["RegistryTableDto"][];
            targetTables?: components["schemas"]["RegistryTableDto"][];
            ddlTables?: components["schemas"]["RegistryTableDto"][];
            layers?: string[];
        };
        RegistryTableDto: {
            name?: string;
            columns?: string[];
            usedByRecipes?: string[];
            variants?: components["schemas"]["RegistryVariantDto"][];
        };
        RegistryVariantDto: {
            columns?: components["schemas"]["RegistryColumnDto"][];
            mappingDirs?: string[];
        };
        RecipeHistoryEntryDto: {
            version?: string;
            timestamp?: string;
            /** Format: int64 */
            sizeBytes?: number;
        };
        B15RowDto: {
            clusterName?: string;
            recipeFilename?: string;
            jobId?: string;
            appStartIso?: string;
            avgJobDurationInMinsSec?: string;
            status?: string;
            message?: string;
        };
        OperationalSnapshotDto: {
            date?: string;
            rows?: components["schemas"]["B15RowDto"][];
        };
        HistoryEntryDto: {
            date?: string;
            status?: string;
            /** Format: double */
            durationMin?: number;
        };
        OperationalSummaryDto: {
            dates?: string[];
            recipes?: components["schemas"]["RecipeSummaryDto"][];
        };
        RecipeSummaryDto: {
            recipeFilename?: string;
            layer?: string;
            latestDate?: string;
            latestStatus?: string;
            /** Format: int32 */
            okCount?: number;
            /** Format: int32 */
            koCount?: number;
            history?: components["schemas"]["HistoryEntryDto"][];
            /** Format: double */
            avgDurationMin?: number;
            /** Format: double */
            p50DurationMin?: number;
            /** Format: double */
            p95DurationMin?: number;
            lastJobId?: string;
            lastClusterName?: string;
        };
        RunDto: {
            date?: string;
            clusterName?: string;
            jobId?: string;
            appStartIso?: string;
            /** Format: double */
            durationMin?: number;
            status?: string;
            message?: string;
        };
        RunsDto: {
            /** Format: int32 */
            limit?: number;
            byRecipe?: {
                [key: string]: components["schemas"]["RunDto"][];
            };
        };
        OperationalDatesDto: {
            dates?: string[];
            mode?: string;
        };
        ClusterIndexDto: {
            mode?: string;
            dates?: string[];
            totals?: components["schemas"]["TotalsDto"];
            clusters?: components["schemas"]["ClusterSummaryDto"][];
        };
        ClusterSummaryDto: {
            name?: string;
            /** Format: int32 */
            recipeCount?: number;
            dateIdx?: number[];
            /** Format: int32 */
            rows?: number;
            /** Format: int32 */
            ok?: number;
            /** Format: int32 */
            ko?: number;
            lastDate?: string;
            lastStatus?: string;
        };
        TotalsDto: {
            /** Format: int32 */
            clusters?: number;
            /** Format: int32 */
            recipes?: number;
            /** Format: int32 */
            dates?: number;
            /** Format: int32 */
            rows?: number;
        };
        ClusterDetailDto: {
            name?: string;
            dates?: string[];
            recipes?: components["schemas"]["RecipeInClusterDto"][];
        };
        RecipeInClusterDto: {
            recipeFilename?: string;
            layer?: string;
            dateIdx?: number[];
            /** Format: int32 */
            rows?: number;
            /** Format: int32 */
            ok?: number;
            /** Format: int32 */
            ko?: number;
            lastDate?: string;
            lastStatus?: string;
        };
        ConnectorDto: {
            fromField?: string;
            fromInstance?: string;
            fromInstanceType?: string;
            toField?: string;
            toInstance?: string;
            toInstanceType?: string;
        };
        FieldDependencyDto: {
            inputField?: string;
            outputField?: string;
        };
        FolderDto: {
            name?: string;
            group?: string;
            owner?: string;
            shared?: string;
            description?: string;
            permissions?: string;
            uuid?: string;
            sources?: components["schemas"]["SourceDto"][];
            targets?: components["schemas"]["TargetDto"][];
            transformations?: components["schemas"]["TransformationDto"][];
            mapplets?: components["schemas"]["MappletDto"][];
            mappings?: components["schemas"]["MappingDto"][];
        };
        GroupDto: {
            description?: string;
            name?: string;
            expression?: string;
            order?: string;
            type?: string;
        };
        InstanceDto: {
            description?: string;
            name?: string;
            reusable?: string;
            transformationName?: string;
            transformationType?: string;
            tType?: string;
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
        };
        MappingDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            targetLoader?: components["schemas"]["TargetLoaderDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MappingModelDto: {
            creationDate?: string;
            repositoryVersion?: string;
            repository?: components["schemas"]["RepositoryDto"];
        };
        MappingVariableDto: {
            aggfunction?: string;
            dataType?: string;
            defaultValue?: string;
            description?: string;
            isExpressionVariable?: string;
            isParam?: string;
            name?: string;
            precision?: string;
            scale?: string;
            userDefined?: string;
        };
        MappletDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MetadataExtensionDto: {
            datatype?: string;
            description?: string;
            domainname?: string;
            isclienteditable?: string;
            isclientvisible?: string;
            isreusable?: string;
            isshareread?: string;
            issharewrite?: string;
            maxlength?: string;
            name?: string;
            value?: string;
            vendorname?: string;
        };
        RepositoryDto: {
            name?: string;
            version?: string;
            codepage?: string;
            databaseType?: string;
            folder?: components["schemas"]["FolderDto"];
        };
        SourceDto: {
            name?: string;
            businessname?: string;
            databasetype?: string;
            dbdname?: string;
            description?: string;
            objectversion?: string;
            ownername?: string;
            versionnumber?: string;
            sourceFields?: components["schemas"]["SourceFieldDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
        };
        SourceFieldDto: {
            businessname?: string;
            dataType?: string;
            description?: string;
            fieldnumber?: string;
            fieldproperty?: string;
            fieldType?: string;
            hidden?: string;
            keyType?: string;
            length?: string;
            level?: string;
            name?: string;
            nullable?: string;
            occurs?: string;
            offset?: string;
            physicallength?: string;
            physicaloffset?: string;
            picturetext?: string;
            precision?: string;
            scale?: string;
            usageflags?: string;
        };
        TableAttributeDto: {
            name?: string;
            value?: string;
        };
        TargetDto: {
            businessName?: string;
            constraint?: string;
            databaseType?: string;
            description?: string;
            name?: string;
            objectVersion?: string;
            tableOptions?: string;
            versionNumber?: string;
            targetFields?: components["schemas"]["TargetFieldDto"][];
        };
        TargetFieldDto: {
            businessName?: string;
            dataType?: string;
            description?: string;
            /** Format: int32 */
            fieldNumber?: number;
            keyType?: string;
            name?: string;
            nullable?: string;
            pictureText?: string;
            precision?: string;
            scale?: string;
        };
        TargetLoaderDto: {
            order?: string;
            targetInstance?: string;
        };
        TransformFieldDto: {
            dataType?: string;
            name?: string;
            defaultValue?: string;
            description?: string;
            group?: string;
            expression?: string;
            expressionType?: string;
            mappletGroup?: string;
            pictureText?: string;
            portType?: string;
            precision?: string;
            refField?: string;
            refInstanceType?: string;
            refSourceField?: string;
            scale?: string;
        };
        TransformationDto: {
            description?: string;
            name?: string;
            objectVersion?: string;
            reusable?: string;
            typ?: string;
            templateName?: string;
            versionNumber?: string;
            transformFields?: components["schemas"]["TransformFieldDto"][];
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
            groups?: components["schemas"]["GroupDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
            fieldDependencies?: components["schemas"]["FieldDependencyDto"][];
            sourceFields?: components["schemas"]["SourceFieldDto"][];
        };
        XmlNodeDto: {
            name?: string;
            attributes?: {
                [key: string]: string;
            };
            text?: string;
            children?: components["schemas"]["XmlNodeDto"][];
        };
        IpcConnectionDto: {
            sourceKind?: string;
            mayFeed?: string[];
            /** Format: int32 */
            exactly?: number;
            namedInputs?: string[];
            active?: boolean;
        };
        IpcKeySpecDto: {
            key?: string;
            parserType?: string;
            required?: boolean;
            widget?: string;
            ruleId?: string;
        };
        IpcRuleMetaDto: {
            id?: string;
            severity?: string;
            statement?: string;
            parserRef?: string;
            ipcRef?: string;
            wikiRef?: string;
        };
        IpcRulesDto: {
            rules?: components["schemas"]["IpcRuleMetaDto"][];
            typeAliases?: {
                [key: string]: string;
            };
            keyAliases?: {
                [key: string]: string;
            };
            keySchema?: {
                [key: string]: components["schemas"]["IpcKeySpecDto"][];
            };
            connections?: {
                [key: string]: components["schemas"]["IpcConnectionDto"];
            };
        };
        ExpressionEntryDto: {
            mappingPath?: string;
            layer?: string;
            transformation?: string;
            port?: string;
            formula?: string;
            origin?: string;
        };
        ControlSchema: {
            configured?: string;
            resolvedReal?: string;
            realExists?: boolean;
            requiredChild?: string;
            realUsable?: boolean;
            mockPath?: string;
            mockUsable?: boolean;
            tier?: string;
            status?: string;
            hint?: string;
            scan?: components["schemas"]["Scan"];
        };
        DiagnosticsDto: {
            status?: string;
            corpus?: components["schemas"]["RootStatus"];
            dwhControl?: components["schemas"]["ControlSchema"];
            composer?: components["schemas"]["RootStatus"];
        };
        FileScan: {
            path?: string;
            /** Format: int64 */
            bytes?: number;
            /** Format: int32 */
            anchorHits?: number;
            /** Format: int32 */
            rowsParsed?: number;
            /** Format: int32 */
            rowsSkipped?: number;
            firstSkipReason?: string;
        };
        InsertTarget: {
            table?: string;
            /** Format: int32 */
            count?: number;
        };
        RootStatus: {
            name?: string;
            configured?: string;
            resolved?: string;
            exists?: boolean;
            requiredChild?: string;
            tier?: string;
            status?: string;
            hint?: string;
            counts?: {
                [key: string]: number;
            };
        };
        Scan: {
            anchorTable?: string;
            anchor?: string;
            expectedLayerDirs?: string[];
            presentDirs?: string[];
            unexpectedDirs?: string[];
            /** Format: int32 */
            filesRead?: number;
            /** Format: int32 */
            anchorHits?: number;
            /** Format: int32 */
            rowsParsed?: number;
            /** Format: int32 */
            rowsSkipped?: number;
            files?: components["schemas"]["FileScan"][];
            insertTargetsFound?: components["schemas"]["InsertTarget"][];
        };
        AppConfigDto: {
            gcpProjectId?: string;
            region?: string;
            dataprocJobUrl?: string;
            dataprocClusterUrl?: string;
            loggingUrl?: string;
            loggingDuration?: string;
            bigQueryUrl?: string;
            dwhControlMode?: string;
            composerMode?: string;
            corpusRoot?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeSaveRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayoutDto"];
                };
            };
        };
    };
    save_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LayoutDto"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeValidationDto"];
                };
            };
        };
    };
    rollback: {
        parameters: {
            query: {
                version: string;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    fanIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FanInRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FanInVerdictsDto"];
                };
            };
        };
    };
    tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeNodeDto"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SummaryDto"];
                };
            };
        };
    };
    relationships: {
        parameters: {
            query?: {
                clusters?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RelationshipsDto"];
                };
            };
        };
    };
    registry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegistryDto"];
                };
            };
        };
    };
    historyVersion_1: {
        parameters: {
            query: {
                version: string;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeHistoryEntryDto"][] | components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalSnapshotDto"];
                };
            };
        };
    };
    summary_1: {
        parameters: {
            query?: {
                clusters?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalSummaryDto"];
                };
            };
        };
    };
    runs: {
        parameters: {
            query: {
                recipe: string[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunsDto"];
                };
            };
        };
    };
    dates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationalDatesDto"];
                };
            };
        };
    };
    clusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterIndexDto"];
                };
            };
        };
    };
    cluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClusterDetailDto"];
                };
            };
        };
    };
    model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MappingModelDto"];
                };
            };
        };
    };
    dom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["XmlNodeDto"];
                };
            };
        };
    };
    rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IpcRulesDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    expressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpressionEntryDto"][];
                };
            };
        };
    };
    diagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DiagnosticsDto"];
                };
            };
        };
    };
    ddl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["JsonNode"];
                    };
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppConfigDto"];
                };
            };
        };
    };
}
