/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/model/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/dom/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["expressions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ddl/{*path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ddl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TreeNodeDto: {
            name?: string;
            path?: string;
            kind?: string;
            layer?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            mappingPath?: string;
            hasRecipe?: boolean;
            hasDdl?: boolean;
            children?: components["schemas"]["TreeNodeDto"][];
        };
        JsonNode: Record<string, never>;
        RecipeDto: {
            path?: string;
            fileName?: string;
            /** Format: int64 */
            sizeBytes?: number;
            modifiedAt?: string;
            content?: components["schemas"]["JsonNode"];
        };
        ConnectorDto: {
            fromField?: string;
            fromInstance?: string;
            fromInstanceType?: string;
            toField?: string;
            toInstance?: string;
            toInstanceType?: string;
        };
        FieldDependencyDto: {
            inputField?: string;
            outputField?: string;
        };
        FolderDto: {
            name?: string;
            group?: string;
            owner?: string;
            shared?: string;
            description?: string;
            permissions?: string;
            uuid?: string;
            sources?: components["schemas"]["SourceDto"][];
            targets?: components["schemas"]["TargetDto"][];
            transformations?: components["schemas"]["TransformationDto"][];
            mapplets?: components["schemas"]["MappletDto"][];
            mappings?: components["schemas"]["MappingDto"][];
        };
        GroupDto: {
            description?: string;
            name?: string;
            expression?: string;
            order?: string;
            type?: string;
        };
        InstanceDto: {
            description?: string;
            name?: string;
            reusable?: string;
            transformationName?: string;
            transformationType?: string;
            tType?: string;
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
        };
        MappingDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            targetLoader?: components["schemas"]["TargetLoaderDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MappingModelDto: {
            creationDate?: string;
            repositoryVersion?: string;
            repository?: components["schemas"]["RepositoryDto"];
        };
        MappingVariableDto: {
            aggfunction?: string;
            dataType?: string;
            defaultValue?: string;
            description?: string;
            isExpressionVariable?: string;
            isParam?: string;
            name?: string;
            precision?: string;
            scale?: string;
            userDefined?: string;
        };
        MappletDto: {
            description?: string;
            isValid?: string;
            name?: string;
            objectVersion?: string;
            versionNumber?: string;
            transformations?: components["schemas"]["TransformationDto"][];
            instances?: components["schemas"]["InstanceDto"][];
            connectors?: components["schemas"]["ConnectorDto"][];
            mappingVariables?: components["schemas"]["MappingVariableDto"][];
        };
        MetadataExtensionDto: {
            datatype?: string;
            description?: string;
            domainname?: string;
            isclienteditable?: string;
            isclientvisible?: string;
            isreusable?: string;
            isshareread?: string;
            issharewrite?: string;
            maxlength?: string;
            name?: string;
            value?: string;
            vendorname?: string;
        };
        RepositoryDto: {
            name?: string;
            version?: string;
            codepage?: string;
            databaseType?: string;
            folder?: components["schemas"]["FolderDto"];
        };
        SourceDto: {
            name?: string;
            businessname?: string;
            databasetype?: string;
            dbdname?: string;
            description?: string;
            objectversion?: string;
            ownername?: string;
            versionnumber?: string;
            sourceFields?: components["schemas"]["SourceFieldDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
        };
        SourceFieldDto: {
            businessname?: string;
            dataType?: string;
            description?: string;
            fieldnumber?: string;
            fieldproperty?: string;
            fieldType?: string;
            hidden?: string;
            keyType?: string;
            length?: string;
            level?: string;
            name?: string;
            nullable?: string;
            occurs?: string;
            offset?: string;
            physicallength?: string;
            physicaloffset?: string;
            picturetext?: string;
            precision?: string;
            scale?: string;
            usageflags?: string;
        };
        TableAttributeDto: {
            name?: string;
            value?: string;
        };
        TargetDto: {
            businessName?: string;
            constraint?: string;
            databaseType?: string;
            description?: string;
            name?: string;
            objectVersion?: string;
            tableOptions?: string;
            versionNumber?: string;
            targetFields?: components["schemas"]["TargetFieldDto"][];
        };
        TargetFieldDto: {
            businessName?: string;
            dataType?: string;
            description?: string;
            /** Format: int32 */
            fieldNumber?: number;
            keyType?: string;
            name?: string;
            nullable?: string;
            pictureText?: string;
            precision?: string;
            scale?: string;
        };
        TargetLoaderDto: {
            order?: string;
            targetInstance?: string;
        };
        TransformFieldDto: {
            dataType?: string;
            name?: string;
            defaultValue?: string;
            description?: string;
            group?: string;
            expression?: string;
            expressionType?: string;
            mappletGroup?: string;
            pictureText?: string;
            portType?: string;
            precision?: string;
            refField?: string;
            refInstanceType?: string;
            refSourceField?: string;
            scale?: string;
        };
        TransformationDto: {
            description?: string;
            name?: string;
            objectVersion?: string;
            reusable?: string;
            typ?: string;
            templateName?: string;
            versionNumber?: string;
            transformFields?: components["schemas"]["TransformFieldDto"][];
            tableAttributeFields?: components["schemas"]["TableAttributeDto"][];
            groups?: components["schemas"]["GroupDto"][];
            metadataExtensions?: components["schemas"]["MetadataExtensionDto"][];
            fieldDependencies?: components["schemas"]["FieldDependencyDto"][];
            sourceFields?: components["schemas"]["SourceFieldDto"][];
        };
        XmlNodeDto: {
            name?: string;
            attributes?: {
                [key: string]: string;
            };
            text?: string;
            children?: components["schemas"]["XmlNodeDto"][];
        };
        ExpressionEntryDto: {
            mappingPath?: string;
            layer?: string;
            transformation?: string;
            port?: string;
            formula?: string;
            origin?: string;
        };
        AppConfigDto: {
            projectId?: string;
            region?: string;
            dataprocJobUrl?: string;
            dataprocClusterUrl?: string;
            loggingUrl?: string;
            dwhControlMode?: string;
            composerMode?: string;
            corpusRoot?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeNodeDto"];
                };
            };
        };
    };
    recipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecipeDto"];
                };
            };
        };
    };
    model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MappingModelDto"];
                };
            };
        };
    };
    dom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["XmlNodeDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    expressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExpressionEntryDto"][];
                };
            };
        };
    };
    ddl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["JsonNode"];
                    };
                };
            };
        };
    };
    config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppConfigDto"];
                };
            };
        };
    };
}
